version: "3.1"
services:
  crossbar:
    image: crossbario/crossbar:latest
    ports:
      - "8080:8080"
    volumes:
      - ./.crossbar:/node/.crossbar
      - ./web:/node/web
      - ./authenticator.py:/node/authenticator.py